<?php

namespace Database\Seeders;

use App\Models\IncidentType;
use App\Models\Keyword;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $keywords = [
            'FIRE' =>   [
                        // English
                        "Fire",
                        "Flames",
                        "Burning",
                        "Blaze",
                        "Inferno",
                        "Wildfire",
                        "Bonfire",
                        "Smoldering",
                        "Embers",
                        "Combustion",
                        "Forest fire",
                        "House fire",
                        "Electrical fire",
                        "Gas explosion",
                        "Fire alarm",
                        "Uncontrolled flames",
                        "Fire hazard",
                        "Fire outbreak",
                        "Heavy smoke",
                        "Rescue operation",
                        "Building on fire",
                        "Emergency fire",
                        "Fire spreading",
                        "Exploding gas tank",
                        "Overheated wires",
                        "Burning car",
                        "Warehouse fire",
                        "Fire department needed",
                        "Collapsed due to fire",
                        "Flammable materials burning",
                        "Thick black smoke",
                        "Firefighters required",
                        "Massive explosion",
                        "Smoke inhalation",
                        "Gas leak explosion",
                        "Fire caused by short circuit",
                        "Severe fire damage",
                        "Trapped inside burning house",
                        // Filipino
                        "Sunog",
                        "Apoy",
                        "Nagliliyab",
                        "Usok",
                        "Pagsiklab",
                        "Nagniningas",
                        "Alarma sa sunog",
                        "Natupok",
                        "Nasunog",
                        "Pinatay ang apoy",
                        "Nilamon ng apoy",
                        "Sobrang init",
                        "Pagsabog",
                        "Nasisira ang bahay",
                        "Panganib sa apoy",
                        "Tumakas sa sunog",
                        "Walang kontrol na apoy",
                        "Pagsiklab ng sunog",
                        "Abandunadong gusali nasunog",
                        "Nasira ang bahay",
                        "Makapal na usok",
                        "Bahay nasusunog",
                        "Kotse nasusunog",
                        "Delikadong apoy",
                        "Wiring na sumabog",
                        "Tumawag ng bombero",
                        "Nakapagpaputok ng apoy",
                        "Pagsabog ng tangke ng gas",
                        "Nasusunog na puno",
                        "Biglang pagsiklab ng apoy",
                        "Sumabog ang kalan",
                        "Nangangamoy sunog",
                        "Init na nagdulot ng sunog",
                        "Natutupok ang gusali",
                        "Sunog sa paaralan",
                        "Aksidenteng pagsunog",
                        // Ilocano
                        "Pannakalay",
                        "Apuy",
                        "Naglalagablab",
                        "Nagparparot",
                        "Agpupuor",
                        "Nagsinder",
                        "Nalablab",
                        "Agdardarep",
                        "Urat ti apuy",
                        "Nalatak",
                        "Puskol",
                        "Narugrug",
                        "Nasiram ti balay",
                        "Napuor ti gasolin",
                        "Napuskol ti pabrika",
                        "Insidente ti sunog",
                        "Pagsardeng ti apoy",
                        "Pagrugrug ti balay",
                        "Pasamak ti nalablab",
                        "Napudot unay",
                        //ibanag
                        "Akaddow",
                        "Apoy",
                        "Nataggisi",
                        "Natutunaw",
                        "Napugaw",
                        "Naglalaga",
                        "Naparyos",
                        "Natagtago",
                        "Nabannug",
                        "Natuturug",
                        "Naputrug",
                        "Mapanunog",
                        "Maputkut",
                        "Mabbannug a balay",
                        "Nabannug a pabrika",
                        "Naglaba a apoy",
                        "Natamwak",
                        "Mababbannug",
                        "Napaturun a apoy",
                        "Napatot",
                    ],


            'CRIME' => [//english
                        "Crime",
                        "Robbery",
                        "Theft",
                        "Assault",
                        "Murder",
                        "Shooting",
                        "Burglary",
                        "Kidnapping",
                        "Fraud",
                        "Stabbing",
                        "Carjacking",
                        "Drug dealing",
                        "Smuggling",
                        "Pickpocketing",
                        "Trespassing",
                        "Extortion",
                        "Homicide",
                        "Harassment",
                        "Vandalism",
                        "Arson",
                        "Breaking and entering",
                        "Shoplifting",
                        "Domestic violence",
                        "Cybercrime",
                        "Identity theft",
                        "Bribery",
                        "Corruption",
                        "Scam",
                        "Forgery",
                        "Illegal gambling",
                        "Blackmail",
                        "Money laundering",
                        "Human trafficking",
                        "Sexual assault",
                        "Gang violence",
                        "Attempted murder",
                        "Road rage attack",
                        "Hit-and-run",
                        "Threats of violence",
                        "Rape",
                        "Swindling",
                        "Public disturbance",
                        "Illegal firearms possession",
                        
                        //tagalog
                        "Krimen",
                        "Patay",
                        "Pinatay",
                        "Saksak",
                        "Sinaksak",
                        "Nakawan",
                        "Pagnanakaw",
                        "Pang-aagaw",
                        "Pagpatay",
                        "Barilan",
                        "Pagnanakaw sa bahay",
                        "Pagtangay",
                        "Pandaraya",
                        "Pananaksak",
                        "Agaw-kotse",
                        "Pagtutulak ng droga",
                        "Pasabog",
                        "Panghoholdap",
                        "Pambubugbog",
                        "Pananakot",
                        "Pangha-harass",
                        "Pananamsam",
                        "Panghohostage",
                        "Pagsunog ng ari-arian",
                        "Pasok nang walang pahintulot",
                        "Pagpapanggap sa internet",
                        "Panloloko sa online",
                        "Pagkukubli ng kita (money laundering)",
                        "Pagpapanggap gamit ang pekeng ID",
                        "Pang-aabuso sa pamilya",
                        "Pagpapalaganap ng pekeng balita (fake news)",
                        "Pagnanakaw sa tindahan (shoplifting)",
                        "Panunuhol",
                        "Pagpapanggap bilang opisyal",
                        "Pag-iiskam",
                        "Pagpapalsipika ng dokumento",
                        "Pagsasabwatan sa krimen",
                        "Panggugulo sa pampublikong lugar",
                        "Pagbebenta ng pekeng produkto",
                        "Pagdadala ng ilegal na baril",
                        "Paninirang-puri",
                        "Pagtakas sa pulisya",
                        "Pagsamantala sa bata",
                        "Pagtatangkang pagpatay",
                        "Pananakit sa lansangan (road rage)",
                        "Paninira ng pribadong ari-arian",
                    //ilocano
                        "Krimen",
                        "Panagnakaw",
                        "Panagbuteng",
                        "Panagpatay",
                        "Panagbabaril",
                        "Panagdanon",
                        "Panagtambang",
                        "Panagnanak",
                        "Panagsuba",
                        "Panagsuksuk",
                        "Panagdupil",
                        "Panagbuteng ti kalsada",
                        "Panagbirok ti tao",
                        "Panaglapastangan",
                        "Panagkidnap",
                        "Panagsala",
                        "Panagpungtot",
                        "Panagkapid",
                        "Panagbuang",
                        "Panagnalawag",
                        //ibanag
                        "Krimen",
                        "Kinawat",
                        "Karabot",
                        "Natay",
                        "Barilan",
                        "Binuno",
                        "Narukay",
                        "Napangilo",
                        "Nalayyak",
                        "Nadayyo",
                        "Natapayas",
                        "Pananaksak",
                        "Nadarayaw",
                        "Napanguk",
                        "Naawat",
                        "Pinasan",
                        "Tinadtem",
                        "Napuskol",
                        "Nakaryam",
                        "Nagkamali",],

            'ROAD' => [//english
                               "Car crash",
                                "Collision",
                                "Hit and run",
                                "Vehicle accident",
                                "Road mishap",
                                "Overturned vehicle",
                                "Truck accident",
                                "Motorcycle accident",
                                "Pedestrian hit",
                                "Traffic incident",
                                "Reckless driving",
                                "Brake failure",
                                "Speeding accident",
                                "Car flipped over",
                                "Swerving incident",
                                "Expressway crash",
                                "Intersection accident",
                                "Drunk driving accident",
                                "Highway accident",
                                "Multiple vehicle collision",
                                "Bridge accident",
                                "Tire blowout",
                                "Lane swerving",
                                "Wrong-way driving",
                                "Sudden brake failure",
                                "Bus accident",
                                "Train collision",
                                "Bicycle hit",
                                "Jaywalker accident",
                                "Pedestrian crossing accident",
                                "Runaway vehicle",
                                "Rollover accident",
                                "Side-impact collision",
                                "T-bone accident",
                                "Car caught fire after crash",
                                "Emergency vehicle accident",
                                "Oil spill accident",
                                "Fog-related crash",
                                "Bridge collapse".
                                //tagalog
                                "Aksidente",
                                "Banggaan",
                                "Takbuhan",
                                "Salpukan",
                                "Nabangga",
                                "Tumaob ang sasakyan",
                                "Nabangga ng truck",
                                "Nabundol",
                                "Nasagasaan",
                                "Dulas sa kalsada",
                                "Nasira ang preno",
                                "Tumagilid ang sasakyan",
                                "Sobrang bilis",
                                "Tumilapon",
                                "Nabangga sa intersection",
                                "Nawasak ang sasakyan",
                                "Bumangga sa pader",
                                "Tinalon ng sasakyan",
                                "Natumbok sa poste",
                                "Nakaladkad sa kalsada",
                                //ilocano
                                "Aksidente",
                                "Nabunggo",
                                "Pannakasagid",
                                "Nabangedan",
                                "Panaglabsing ti kalsada",
                                "Naatiddog ti tinamaan",
                                "Panagranggay",
                                "Nabangga ti jeep",
                                "Naikapas sa kalsada",
                                "Napukpok ti motmot",
                                "Napukaw ti brake",
                                "Agpalpalagto",
                                "Pumanaw sa kalsada",
                                "Napukaw ti kontrol",
                                "Nadayag nga banggaan",
                                "Naistrek ti tricycle",
                                "Panagtungpal ti karburador",
                                "Narurumen ti driver",
                                "Nadaddaras a pagtakder",
                                "Natapayas nga pasamak",
                                //ibanag
                                "Aksidente",
                                "Banggaan",
                                "Takbuhan",
                                "Salpukan",
                                "Nabangga",
                                "Tumaob ang sasakyan",
                                "Nabangga ng truck",
                                "Nabundol",
                                "Nasagasaan",
                                "Dulas sa kalsada",
                                "Nasira ang preno",
                                "Tumagilid ang sasakyan",
                                "Sobrang bilis",
                                "Tumilapon",
                                "Nabangga sa intersection",
                                "Nawasak ang sasakyan",
                                "Bumangga sa pader",
                                "Tinalon ng sasakyan",
                                "Natumbok sa poste",
                                "Nakaladkad sa kalsada",
                                "Nahulog sa bangin",
                                "Bumulusok ang sasakyan",
                                "Kotse nasunog matapos bumangga",
                                "Pagbangga sa barrier",
                                "Nasira ang makina sa gitna ng kalsada",
                                "Tumagilid ang bus",
                                "Nabangga sa tren",
                                "Nabangga habang tumatawid",
                                "Trak na nawalan ng preno",
                                "Nahulog sa tulay",
                                "Pagbangga dahil sa madulas na kalsada",
                                "Nagkarambola sa highway",
                                "Sumabog ang gulong",
                                "Kotse lumipad sa ere",
                                "Pagtama sa guardrail",
                                "Nagsalpukan sa likod",
                                "Inararo ng truck ang mga sasakyan", ],

                    'DISASTER' => [//english
                                    "Earthquake",
                                    "Flood",
                                    "Landslide",
                                    "Storm",
                                    "Typhoon",
                                    "Tsunami",
                                    "Volcanic eruption",
                                    "Flash flood",
                                    "Tornado",
                                    "Hailstorm",
                                    "Hurricane",
                                    "Avalanche",
                                    "Heavy rain",
                                    "Drought",
                                    "Aftershock",
                                    "Wildfire",
                                    "Monsoon",
                                    "Dam collapse",
                                    "Severe thunderstorm",
                                    "Sandstorm",
                                    "Cyclone",
                                    "Storm surge",
                                    "Tropical depression",
                                    "Strong winds",
                                    "Blizzard",
                                    "Extreme heatwave",
                                    "Extreme cold wave",
                                    "Bridge collapse",
                                    "Sinkhole",
                                    "Mudslide",
                                    "River overflow",
                                    "Coastal flooding",
                                    "Storm damage",
                                    "Gas explosion",
                                    "Toxic chemical spill",
                                    "Nuclear disaster",
                                    "Environmental contamination",
                                    "Seismic activity",
                                    "Fault line movement",
                                    "Building collapse",
                                    //tagalog
                                    "Lindol",
                                    "Baha",
                                    "Pagguho ng lupa",
                                    "Bagyo",
                                    "Malakas na ulan",
                                    "Malakas na hangin",
                                    "Pagsabog ng bulkan",
                                    "Pagtaas ng tubig",
                                    "Pagguho ng bundok",
                                    "Daluyong",
                                    "Pag-init ng panahon",
                                    "Kakulangan sa tubig",
                                    "Matinding hangin",
                                    "Buhawi",
                                    "Pagsira ng mga bahay",
                                    "Nawalan ng kuryente",
                                    "Pagkasira ng pananim",
                                    "Pagsira ng tulay",
                                    "Pagkawasak ng daan",
                                    "Pagkalat ng sakit",
                                    "Matinding tagtuyot",
                                    "Nabawasan ang suplay ng tubig",
                                    "Lumubog ang kalsada",
                                    "Pagkasira ng poste ng kuryente",
                                    "Pangangailangan ng rescue operation",
                                    "Nawasak ang mga gusali",
                                    "Pagguho ng pader",
                                    "Nawasak ang kabuhayan",
                                    "Sobrang taas ng tubig baha",
                                    "Nasira ang irigasyon",
                                    "Kalat na mga basura sa baha",
                                    "Pangangailangan ng relief operation",
                                    "Sobrang init na panahon",
                                    "Sunog sa gubat",
                                    "Sumabog ang gas",
                                    "Taggutom",
                                    "Paglabas ng asupre mula sa bulkan",
                                    "Nawasak ang bubong ng bahay",
                                    "Nawasak ang tulay dahil sa baha",
                                    //ilocano
                                    "Linteg",
                                    "Inalapas",
                                    "Panagdalupop",
                                    "Agsaplit",
                                    "Panagbabagyo",
                                    "Panaglipay",
                                    "Panaglapud",
                                    "Panagtudu",
                                    "Panagdalan ti tayab",
                                    "Panagubog",
                                    "Panagdadagsen",
                                    "Panagdukal ti daga",
                                    "Panagkapoy ti arubayan",
                                    "Panagpaltog ti dadduma",
                                    "Panagtaeng ti lasag",
                                    "Panaglaylay ti rango",
                                    "Agpungtot ti init",
                                    "Panagpalangoy ti babaen",
                                    "Panagpanggap",
                                    "Panagrinatrina",
                                    //ibanag
                                    "Linug",
                                    "Baha",
                                    "Tabbaya",
                                    "Baggiu",
                                    "Tangabbong",
                                    "Tarakayan",
                                    "Pagguguho",
                                    "Narakupay",
                                    "Lalayo",
                                    "Paggigi",
                                    "Katang tanglaw",
                                    "Nanapuya",
                                    "Nabboboy",
                                    "Nalyateng",
                                    "Matunaw",
                                    "Naragapay",
                                    "Namuddak",
                                    "Piggugui",
                                    "Nasaguwan",
                                    "Naparay",],
                            
            'HEALTH' => [//english
                                  "Heart attack",
                                    "Stroke",
                                    "Injury",
                                    "Unconscious",
                                    "Difficulty breathing",
                                    "Seizure",
                                    "High fever",
                                    "Bleeding",
                                    "Poisoning",
                                    "Choking",
                                    "Dizziness",
                                    "Fainting",
                                    "Allergic reaction",
                                    "Broken bone",
                                    "Infection",
                                    "Severe headache",
                                    "Chest pain",
                                    "Diarrhea",
                                    "Vomiting",
                                    "Burns",
                                    "Fracture",
                                    "Heat stroke",
                                    "Dehydration",
                                    "Severe coughing",
                                    "Food poisoning",
                                    "Loss of consciousness",
                                    "Panic attack",
                                    "Respiratory arrest",
                                    "Cardiac arrest",
                                    "Severe stomach pain",
                                    "High blood pressure",
                                    "Low blood pressure",
                                    "Hypothermia",
                                    "Hyperthermia",
                                    "Septic shock",
                                    "Internal bleeding",
                                    "Electrocution",
                                    "Drowning",
                                    "Skin rash",
                                    "Severe fatigue",
                                    //tagalog
                                    "Atake sa puso",
                                    "Stroke",
                                    "Sugat",
                                    "Hinimatay",
                                    "Nahihirapang huminga",
                                    "Pangingisay",
                                    "Lagnat",
                                    "Dumudugo",
                                    "Nalason",
                                    "Nabilaukan",
                                    "Nahihilo",
                                    "Nawalan ng malay",
                                    "Pangangati",
                                    "Nabali ang buto",
                                    "Impeksyon",
                                    "Matinding sakit ng ulo",
                                    "Pananakit ng dibdib",
                                    "Pagtatae",
                                    "Pagsusuka",
                                    "Napaso",
                                    "Nangisay",
                                    "Matinding ubo",
                                    "Paninikip ng dibdib",
                                    "Sobrang taas ng presyon",
                                    "Biglang bumagsak ang presyon",
                                    "Matinding pananakit ng tiyan",
                                    "Pagkatuyot ng katawan",
                                    "Pagkalunod",
                                    "Paninigas ng katawan",
                                    "Pagkapaso sa kuryente",
                                    "Sobrang panghihina",
                                    "Hirap sa pagsasalita",
                                    "Matinding pagsakit ng kasukasuan",
                                    "Nahimatay sa init",
                                    "Nilalagnat nang matagal",
                                    "Nangitim ang katawan",
                                    "Pananakit ng likod at balakang",
                                    "Pagkawala ng malay ng matagal",
                                    //ilocano
                                    "Apektado ti puso",
                                    "Stroke",
                                    "Nasugatan",
                                    "Nagkaro ti agmalmalem",
                                    "Masikog ti angot",
                                    "Nagpaltog",
                                    "Pugot ti baba",
                                    "Natadtaudan",
                                    "Napudot unay",
                                    "Nadadael ti bagis",
                                    "Nalason",
                                    "Nalinglingad",
                                    "Nagapoy ti panunot",
                                    "Nalaing ti dayta",
                                    "Pinagbabasura",
                                    "Nabali ti tulang",
                                    "Nadadael ti ulo",
                                    "Nabirok ti agmalmalem",
                                    "Narugit unay",
                                    "Nagsangit",
                                    //ibanag
                                     "Napigilan ti puso",
                                    "Stroke",
                                    "Nabutak",
                                    "Nawawan tu linao",
                                    "Naddekut ti angot",
                                    "Narigat ti pagangot",
                                    "Nalaing a gutom",
                                    "Naglalabba",
                                    "Nabutlak",
                                    "Nabayu",
                                    "Naddayu tu ula",
                                    "Nawalan ti malay",
                                    "Nabulun",
                                    "Nataggisi",
                                    "Naglabtu",
                                    "Nababbang ti utun",
                                    "Pinunuy",
                                    "Nalamong",
                                    "Nadikban",
                                    "Napadayat",                                   ],


            'SEA' => [//english
                                "Boat sinking",
                                "Drowning",
                                "Shipwreck",
                                "Capsized",
                                "Lost at sea",
                                "Fishing boat accident",
                                "Overboard",
                                "Ocean rescue",
                                "High tide",
                                "Strong waves",
                                "Maritime distress",
                                "Ship fire",
                                "Underwater accident",
                                "Stranded at sea",
                                "Stuck at coral reefs",
                                "Ferry accident",
                                "Shark attack",
                                "Tsunami warning",
                                "Engine failure",
                                "Life raft rescue",
                                "Oil spill",
                                "Pirate attack",
                                "Sinking vessel",
                                "Ship collision",
                                "Abandoned ship",
                                "Emergency evacuation",
                                "Sailboat overturned",
                                "Flooded cargo hold",
                                "Man overboard",
                                "Severe sea storm",
                                "Submerged vehicle",
                                "Distress signal",
                                "Lifeguard rescue",
                                "Strong underwater current",
                                "Stranded divers",
                                "Boat explosion",
                                "Fishing net entanglement",
                                "Capsized jet ski",
                                "Tanker leak",
                                "Maritime accident",
                                //tagalog
                                "Lumubog ang bangka",
                                "Nalulunod",
                                "Nasira ang barko",
                                "Tumagilid ang bangka",
                                "Nawawala sa dagat",
                                "Banggaan ng bangka",
                                "Nahulog sa dagat",
                                "Pagsagip sa dagat",
                                "Malakas na alon",
                                "Mataas na tubig",
                                "Sakuna sa karagatan",
                                "Sunog sa barko",
                                "Aksidente sa ilalim ng tubig",
                                "Naiwan sa gitna ng dagat",
                                "Sumadsad sa batuhan",
                                "Aksidente sa ferry",
                                "Inatake ng pating",
                                "Babala ng tsunami",
                                "Sira ang makina",
                                "Nailigtas gamit ang lifeboat",
                                "Tagas ng langis",
                                "Inatake ng mga pirata",
                                "Nawasak ang bangka",
                                "Pagbanggaan ng barko",
                                "Pagtakas mula sa lumulubog na barko",
                                "Tumaob ang bangkang pangisda",
                                "Bumagsak sa dagat",
                                "Nasangga ng alon",
                                "Kagyat na paglilikas",
                                "Tumalsik sa tubig",
                                "Naipit sa lambat",
                                "Na-stranded sa isla",
                                "Tinangay ng agos",
                                "Sinalpok ng barko",
                                "Nalunod habang lumalangoy",
                                "Nasagasaan ng bangka",
                                "Nasabugan sa dagat",
                                "Nalusaw ang kargamento sa tubig",
                            //ilocano
                            "Nalunod",
                            "Nabugbog ti dagat",
                            "Naimbuyog ti barko",
                            "Nagsangit ti balud",
                            "Napukaw ti tawtaw",
                            "Napungtot ti ayan",
                            "Nagparpuk ti dagat",
                            "Napaspas ti ayat",
                            "Narugit ti balud",
                            "Nasayaat a turong",
                            "Nadadael ti barko",
                            "Nalipatan ti tayab",
                            "Nabigla ti ayan",
                            "Napatalaw ti ayan",
                            "Narugit ti dagat",
                            "Agawid ti tawtaw",
                            "Nalusayan ti barko",
                            "Napaspas ti kabungod",
                            "Nabigla ti timmoy",
                            "Napukaw ti agtutugaw",
                            //ibanag
                            "Naputkan a bangka",
                            "Nalunog",
                            "Naparit ti dagat",
                            "Napanag babaw",
                            "Nawaganan",
                            "Napakappay a timmoy",
                            "Nabaggon a linawa",
                            "Napupurga",
                            "Narigat a tugot",
                            "Nawanan ti balod",
                            "Nagpatingkad a dagat",
                            "Nababbang ti baroto",
                            "Napanaw a ayan",
                            "Nabarog ti bangka",
                            "Napujul a linawa",
                            "Nasaguwan",
                            "Napan a masikog",
                            "Napagtarayan",
                            "Naglabut a dagat",
                            "Nappaaway",
],
        ];

        foreach ($keywords as $type => $words) {
            $incidentType = IncidentType::where('name', $type)->first();
            if ($incidentType) {
                foreach ($words as $word) {
                    Keyword::create([
                        'incident_type_id' => $incidentType->id,
                        'keyword' => $word,
                    ]);
                }
            }
        }
    }
}
