<?php

namespace Database\Seeders;

use App\Models\IncidentType;
use App\Models\Keyword;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $keywords = [
            'FIRE' =>   [
                        // English
                        "Fire",
                        "Flames",
                        "Burning",
                        "Blaze",
                        "Inferno",
                        "Wildfire",
                        "Bonfire",
                        "Smoldering",
                        "Embers",
                        "Combustion",
                        "Forest fire",
                        "House fire",
                        "Electrical fire",
                        "Gas explosion",
                        "Fire alarm",
                        "Uncontrolled flames",
                        "Fire hazard",
                        "Fire outbreak",
                        "Heavy smoke",
                        "Rescue operation",
                        // Filipino
                        "Sunog",
                        "Apoy",
                        "Nagliliyab",
                        "Usok",
                        "Pagsiklab",
                        "Nagniningas",
                        "Alarma sa sunog",
                        "Natupok",
                        "Nasunog",
                        "Pinatay ang apoy",
                        "Nilamon ng apoy",
                        "Sobrang init",
                        "Pagsabog",
                        "Nasisira ang bahay",
                        "Panganib sa apoy",
                        "Tumakas sa sunog",
                        "Walang kontrol na apoy",
                        "Pagsiklab ng sunog",
                        "Abandunadong gusali nasunog",
                        "Nasira ang bahay",
                        // Ilocano
                        "Pannakalay",
                        "Apuy",
                        "Naglalagablab",
                        "Nagparparot",
                        "Agpupuor",
                        "Nagsinder",
                        "Nalablab",
                        "Agdardarep",
                        "Urat ti apuy",
                        "Nalatak",
                        "Puskol",
                        "Narugrug",
                        "Nasiram ti balay",
                        "Napuor ti gasolin",
                        "Napuskol ti pabrika",
                        "Insidente ti sunog",
                        "Pagsardeng ti apoy",
                        "Pagrugrug ti balay",
                        "Pasamak ti nalablab",
                        "Napudot unay",
                        //ibanag
                        "Akaddow",
                        "Apoy",
                        "Nataggisi",
                        "Natutunaw",
                        "Napugaw",
                        "Naglalaga",
                        "Naparyos",
                        "Natagtago",
                        "Nabannug",
                        "Natuturug",
                        "Naputrug",
                        "Mapanunog",
                        "Maputkut",
                        "Mabbannug a balay",
                        "Nabannug a pabrika",
                        "Naglaba a apoy",
                        "Natamwak",
                        "Mababbannug",
                        "Napaturun a apoy",
                        "Napatot",
                    ],


            'CRIME' => [//english
                        "Crime",
                        "Robbery",
                        "Theft",
                        "Assault",
                        "Murder",
                        "Shooting",
                        "Burglary",
                        "Kidnapping",
                        "Fraud",
                        "Stabbing",
                        "Carjacking",
                        "Drug dealing",
                        "Smuggling",
                        "Pickpocketing",
                        "Trespassing",
                        "Extortion",
                        "Homicide",
                        "Harassment",
                        "Vandalism",
                        "Arson",
                        //tagalog
                        "Krimen",
                        "Nakawan",
                        "Pagnanakaw",
                        "Pang-aagaw",
                        "Pagpatay",
                        "Barilan",
                        "Pagnanakaw sa bahay",
                        "Pagtangay",
                        "Pandaraya",
                        "Pananaksak",
                        "Agaw-kotse",
                        "Pagtutulak ng droga",
                        "Pasabog",
                        "Panghoholdap",
                        "Pambubugbog",
                        "Pananakot",
                        "Pangha-harass",
                        "Pananamsam",
                        "Panghohostage",
                        "Pagsunog ng ari-arian",
                    //ilocano
                        "Krimen",
                        "Panagnakaw",
                        "Panagbuteng",
                        "Panagpatay",
                        "Panagbabaril",
                        "Panagdanon",
                        "Panagtambang",
                        "Panagnanak",
                        "Panagsuba",
                        "Panagsuksuk",
                        "Panagdupil",
                        "Panagbuteng ti kalsada",
                        "Panagbirok ti tao",
                        "Panaglapastangan",
                        "Panagkidnap",
                        "Panagsala",
                        "Panagpungtot",
                        "Panagkapid",
                        "Panagbuang",
                        "Panagnalawag",
                        //ibanag
                        "Krimen",
                        "Kinawat",
                        "Karabot",
                        "Natay",
                        "Barilan",
                        "Binuno",
                        "Narukay",
                        "Napangilo",
                        "Nalayyak",
                        "Nadayyo",
                        "Natapayas",
                        "Pananaksak",
                        "Nadarayaw",
                        "Napanguk",
                        "Naawat",
                        "Pinasan",
                        "Tinadtem",
                        "Napuskol",
                        "Nakaryam",
                        "Nagkamali",],

            'ROAD ACCIDENT' => [//english
                                "Car crash",
                                "Collision",
                                "Hit and run",
                                "Vehicle accident",
                                "Road mishap",
                                "Overturned vehicle",
                                "Truck accident",
                                "Motorcycle accident",
                                "Pedestrian hit",
                                "Traffic incident",
                                "Reckless driving",
                                "Brake failure",
                                "Speeding accident",
                                "Car flipped over",
                                "Swerving incident",
                                "Expressway crash",
                                "Intersection accident",
                                "Drunk driving accident",
                                "Highway accident",
                                "Multiple vehicle collision",
                                //tagalog
                                "Aksidente",
                                "Banggaan",
                                "Takbuhan",
                                "Salpukan",
                                "Nabangga",
                                "Tumaob ang sasakyan",
                                "Nabangga ng truck",
                                "Nabundol",
                                "Nasagasaan",
                                "Dulas sa kalsada",
                                "Nasira ang preno",
                                "Tumagilid ang sasakyan",
                                "Sobrang bilis",
                                "Tumilapon",
                                "Nabangga sa intersection",
                                "Nawasak ang sasakyan",
                                "Bumangga sa pader",
                                "Tinalon ng sasakyan",
                                "Natumbok sa poste",
                                "Nakaladkad sa kalsada",
                                //ilocano
                                "Aksidente",
                                "Nabunggo",
                                "Pannakasagid",
                                "Nabangedan",
                                "Panaglabsing ti kalsada",
                                "Naatiddog ti tinamaan",
                                "Panagranggay",
                                "Nabangga ti jeep",
                                "Naikapas sa kalsada",
                                "Napukpok ti motmot",
                                "Napukaw ti brake",
                                "Agpalpalagto",
                                "Pumanaw sa kalsada",
                                "Napukaw ti kontrol",
                                "Nadayag nga banggaan",
                                "Naistrek ti tricycle",
                                "Panagtungpal ti karburador",
                                "Narurumen ti driver",
                                "Nadaddaras a pagtakder",
                                "Natapayas nga pasamak",
                                //ibanag
                                "Aksidente",
                                "Nabanggà",
                                "Nalabbang",
                                "Nasagasaan",
                                "Tumagilid",
                                "Nabanged",
                                "Nabaggang",
                                "Natagtagan",
                                "Napalagsak",
                                "Paddaddukan",
                                "Naragupay",
                                "Nauneg ti kalsada",
                                "Nagpaspas",
                                "Napalabbang",
                                "Napatiway",
                                "Naiputun",
                                "Namangkè",
                                "Napindun",
                                "Naggandaga",
                                "Napangahaway", ],

            'DISASTER' => [//english
                            "Earthquake",
                            "Flood",
                            "Landslide",
                            "Storm",
                            "Typhoon",
                            "Tsunami",
                            "Volcanic eruption",
                            "Flash flood",
                            "Tornado",
                            "Hailstorm",
                            "Hurricane",
                            "Avalanche",
                            "Heavy rain",
                            "Drought",
                            "Aftershock",
                            "Wildfire",
                            "Monsoon",
                            "Dam collapse",
                            "Severe thunderstorm",
                            "Sandstorm",
                        //tagalog
                        "Lindol",
                        "Baha",
                        "Pagguho ng lupa",
                        "Bagyo",
                        "Malakas na ulan",
                        "Malakas na hangin",
                        "Pagsabog ng bulkan",
                        "Pagtaas ng tubig",
                        "Pagguho ng bundok",
                        "Daluyong",
                        "Pag-init ng panahon",
                        "Kakulangan sa tubig",
                        "Matinding hangin",
                        "Buhawi",
                        "Pagsira ng mga bahay",
                        "Nawalan ng kuryente",
                        "Pagkasira ng pananim",
                        "Pagsira ng tulay",
                        "Pagkawasak ng daan",
                        "Pagkalat ng sakit",
                        //ilocano
                        "Linteg",
                        "Inalapas",
                        "Panagdalupop",
                        "Agsaplit",
                        "Panagbabagyo",
                        "Panaglipay",
                        "Panaglapud",
                        "Panagtudu",
                        "Panagdalan ti tayab",
                        "Panagubog",
                        "Panagdadagsen",
                        "Panagdukal ti daga",
                        "Panagkapoy ti arubayan",
                        "Panagpaltog ti dadduma",
                        "Panagtaeng ti lasag",
                        "Panaglaylay ti rango",
                        "Agpungtot ti init",
                        "Panagpalangoy ti babaen",
                        "Panagpanggap",
                        "Panagrinatrina",
                        //ibanag
                        "Linug",
                        "Baha",
                        "Tabbaya",
                        "Baggiu",
                        "Tangabbong",
                        "Tarakayan",
                        "Pagguguho",
                        "Narakupay",
                        "Lalayo",
                        "Paggigi",
                        "Katang tanglaw",
                        "Nanapuya",
                        "Nabboboy",
                        "Nalyateng",
                        "Matunaw",
                        "Naragapay",
                        "Namuddak",
                        "Piggugui",
                        "Nasaguwan",
                        "Naparay",],
                            
            'HEALTH EMERGENCY' => [//english
                                    "Heart attack",
                                    "Stroke",
                                    "Injury",
                                    "Unconscious",
                                    "Difficulty breathing",
                                    "Seizure",
                                    "High fever",
                                    "Bleeding",
                                    "Poisoning",
                                    "Choking",
                                    "Dizziness",
                                    "Fainting",
                                    "Allergic reaction",
                                    "Broken bone",
                                    "Infection",
                                    "Severe headache",
                                    "Chest pain",
                                    "Diarrhea",
                                    "Vomiting",
                                    "Burns",
                                    //tagalog
                                    "Atake sa puso",
                                    "Stroke",
                                    "Sugat",
                                    "Hinimatay",
                                    "Nahihirapang huminga",
                                    "Pangingisay",
                                    "Lagnat",
                                    "Dumudugo",
                                    "Nalason",
                                    "Nabilaukan",
                                    "Nahihilo",
                                    "Nawalan ng malay",
                                    "Pangangati",
                                    "Nabali ang buto",
                                    "Impeksyon",
                                    "Matinding sakit ng ulo",
                                    "Pananakit ng dibdib",
                                    "Pagtatae",
                                    "Pagsusuka",
                                    "Napaso",
                                    //ilocano
                                    "Apektado ti puso",
                                    "Stroke",
                                    "Nasugatan",
                                    "Nagkaro ti agmalmalem",
                                    "Masikog ti angot",
                                    "Nagpaltog",
                                    "Pugot ti baba",
                                    "Natadtaudan",
                                    "Napudot unay",
                                    "Nadadael ti bagis",
                                    "Nalason",
                                    "Nalinglingad",
                                    "Nagapoy ti panunot",
                                    "Nalaing ti dayta",
                                    "Pinagbabasura",
                                    "Nabali ti tulang",
                                    "Nadadael ti ulo",
                                    "Nabirok ti agmalmalem",
                                    "Narugit unay",
                                    "Nagsangit",
                                    //ibanag
                                     "Napigilan ti puso",
                                    "Stroke",
                                    "Nabutak",
                                    "Nawawan tu linao",
                                    "Naddekut ti angot",
                                    "Narigat ti pagangot",
                                    "Nalaing a gutom",
                                    "Naglalabba",
                                    "Nabutlak",
                                    "Nabayu",
                                    "Naddayu tu ula",
                                    "Nawalan ti malay",
                                    "Nabulun",
                                    "Nataggisi",
                                    "Naglabtu",
                                    "Nababbang ti utun",
                                    "Pinunuy",
                                    "Nalamong",
                                    "Nadikban",
                                    "Napadayat",                                   ],


            'SEA INCIDENT' => [//english
                                "Boat sinking",
                                "Drowning",
                                "Shipwreck",
                                "Capsized",
                                "Lost at sea",
                                "Fishing boat accident",
                                "Overboard",
                                "Ocean rescue",
                                "High tide",
                                "Strong waves",
                                "Maritime distress",
                                "Ship fire",
                                "Underwater accident",
                                "Stranded at sea",
                                "Stuck at coral reefs",
                                "Ferry accident",
                                "Shark attack",
                                "Tsunami warning",
                                "Engine failure",
                                "Life raft rescue",
                                //tagalog
                                "Lumubog ang bangka",
                                "Nalulunod",
                                "Nasira ang barko",
                                "Tumagilid ang bangka",
                                "Nawawala sa dagat",
                                "Banggaan ng bangka",
                                "Nahulog sa dagat",
                                "Pagsagip sa dagat",
                                "Malakas na alon",
                                "Mataas na tubig",
                                "Sakuna sa karagatan",
                                "Sunog sa barko",
                                "Aksidente sa ilalim ng tubig",
                                "Naiwan sa gitna ng dagat",
                                "Sumadsad sa batuhan",
                                "Aksidente sa ferry",
                                "Inatake ng pating",
                                "Babala ng tsunami",
                                "Sira ang makina",
                                "Nailigtas gamit ang lifeboat",
                            //ilocano
                            "Nalunod",
                            "Nabugbog ti dagat",
                            "Naimbuyog ti barko",
                            "Nagsangit ti balud",
                            "Napukaw ti tawtaw",
                            "Napungtot ti ayan",
                            "Nagparpuk ti dagat",
                            "Napaspas ti ayat",
                            "Narugit ti balud",
                            "Nasayaat a turong",
                            "Nadadael ti barko",
                            "Nalipatan ti tayab",
                            "Nabigla ti ayan",
                            "Napatalaw ti ayan",
                            "Narugit ti dagat",
                            "Agawid ti tawtaw",
                            "Nalusayan ti barko",
                            "Napaspas ti kabungod",
                            "Nabigla ti timmoy",
                            "Napukaw ti agtutugaw",
                            //ibanag
                            "Naputkan a bangka",
                            "Nalunog",
                            "Naparit ti dagat",
                            "Napanag babaw",
                            "Nawaganan",
                            "Napakappay a timmoy",
                            "Nabaggon a linawa",
                            "Napupurga",
                            "Narigat a tugot",
                            "Nawanan ti balod",
                            "Nagpatingkad a dagat",
                            "Nababbang ti baroto",
                            "Napanaw a ayan",
                            "Nabarog ti bangka",
                            "Napujul a linawa",
                            "Nasaguwan",
                            "Napan a masikog",
                            "Napagtarayan",
                            "Naglabut a dagat",
                            "Nappaaway",
],
        ];

        foreach ($keywords as $type => $words) {
            $incidentType = IncidentType::where('name', $type)->first();
            if ($incidentType) {
                foreach ($words as $word) {
                    Keyword::create([
                        'incident_type_id' => $incidentType->id,
                        'keyword' => $word,
                    ]);
                }
            }
        }
    }
}
