@extends('layouts.lgu')

@section('content')
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Incident Reports</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title mb-4">
                        @if($call)
                            Call-Based Reports ({{ $call->caller_contact }})
                        @elseif($message)
                            Message-Based Reports ({{ $message->sender_contact }})
                        @else
                            All Generated Reports
                        @endif
                    </h5>
                    
                    @if(session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    
                    @if(session('error'))
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ session('error') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered" id="reportsTable">
                            <thead class="table-light">
                                <tr>
                                    <th>Report Number</th>
                                    <th>Case Number</th>
                                    <th>Incident Type</th>
                                    <th>Generated By</th>
                                    <th>Generation Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($reports as $report)
                                    <tr>
                                        <td>{{ $report->report_number }}</td>
                                        <td>{{ $report->incidentCase->case_number }}</td>
                                        <td>{{ $report->incidentCase->incidentType->name }}</td>
                                        <td>{{ $report->user->profile->firstname.' '.$report->user->profile->lastname ?? 'System' }}</td>
                                        <td>{{ $report->created_at->format('F j, Y h:i A') }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{{ route('lgu.incident_reports.view', $report->id) }}" 
                                                   class="btn btn-sm btn-info" target="_blank">
                                                    <i class="fas fa-eye"></i> View
                                                </a>
                                                <a href="{{ route('lgu.incident_reports.download', $report->id) }}" 
                                                   class="btn btn-sm btn-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center">No reports found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ $source_type == 'call' ? route('lgu.emergencycall.index') : route('lgu.emergencymessage.index') }}" 
                       class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back to {{ $source_type == 'call' ? 'Calls' : 'Messages' }}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $('#reportsTable').DataTable({
            order: [[4, 'desc']]
        });
    });
</script>
@endsection