

<?php $__env->startSection('content'); ?>
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Incident Reports</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title mb-4">
                        <?php if($call): ?>
                            Call-Based Reports (<?php echo e($call->caller_contact); ?>)
                        <?php elseif($message): ?>
                            Message-Based Reports (<?php echo e($message->sender_contact); ?>)
                        <?php else: ?>
                            All Generated Reports
                        <?php endif; ?>
                    </h5>
                    
                    <?php if(session('success')): ?>
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <?php echo e(session('success')); ?>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    <?php endif; ?>
                    
                    <?php if(session('error')): ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <?php echo e(session('error')); ?>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    <?php endif; ?>
                    
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered" id="reportsTable">
                            <thead class="table-light">
                                <tr>
                                    <th>Report Number</th>
                                    <th>Case Number</th>
                                    <th>Incident Type</th>
                                    <th>Generated By</th>
                                    <th>Generation Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td><?php echo e($report->report_number); ?></td>
                                        <td><?php echo e($report->incidentCase->case_number); ?></td>
                                        <td><?php echo e($report->incidentCase->incidentType->name); ?></td>
                                        <td><?php echo e($report->user->profile->firstname.' '.$report->user->profile->lastname ?? 'System'); ?></td>
                                        <td><?php echo e($report->created_at->format('F j, Y h:i A')); ?></td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="<?php echo e(route('bfp.incident_reports.view', $report->id)); ?>" 
                                                   class="btn btn-sm btn-info" target="_blank">
                                                    <i class="fas fa-eye"></i> View
                                                </a>
                                                <a href="<?php echo e(route('bfp.incident_reports.download', $report->id)); ?>" 
                                                   class="btn btn-sm btn-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="6" class="text-center">No reports found</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="<?php echo e($source_type == 'call' ? route('bfp.emergencycall.index') : route('bfp.emergencymessage.index')); ?>" 
                       class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back to <?php echo e($source_type == 'call' ? 'Calls' : 'Messages'); ?>

                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php $__env->startSection('scripts'); ?>
<script>
    $(document).ready(function() {
        $('#reportsTable').DataTable({
            order: [[4, 'desc']]
        });
    });
</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.bfp', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\heroes-app\resources\views/admin/bfp/incidents/index.blade.php ENDPATH**/ ?>