

<?php $__env->startSection('content'); ?>
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">All Incident Reports</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title mb-4">Complete List of Generated Incident Reports</h5>
                    
                    <?php if(session('success')): ?>
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <?php echo e(session('success')); ?>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    <?php endif; ?>
                    
                    <?php if(session('error')): ?>
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <?php echo e(session('error')); ?>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    <?php endif; ?>
                    
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered" id="reportsTable">
                            <thead class="table-light">
                                <tr>
                                    <th>Report Number</th>
                                    <th>Case Number</th>
                                    <th>Incident Type</th>
                                    <th>Source Type</th>
                                    <th>Contact</th>
                                    <th>Generated By</th>
                                    <th>Generation Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $__empty_1 = true; $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td><?php echo e($report->report_number); ?></td>
                                        <td><?php echo e($report->incidentCase->case_number); ?></td>
                                        <td><?php echo e($report->incidentCase->incidentType->name); ?></td>
                                        <td>
                                            <span class="badge bg-<?php echo e($report->source_type == 'call' ? 'success' : ($report->source_type == 'message' ? 'info' : 'secondary')); ?>">
                                                <?php echo e(ucfirst($report->source_type)); ?>

                                            </span>
                                        </td>
                                        <td>
                                            <?php if($report->source_type == 'call' && $report->source): ?>
                                                <?php echo e($report->source->caller_contact); ?>

                                            <?php elseif($report->source_type == 'message' && $report->source): ?>
                                                <?php echo e($report->source->sender_contact); ?>

                                            <?php else: ?>
                                                N/A
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo e($report->user->profile->firstname.' '.$report->user->profile->lastname ?? 'System'); ?></td>
                                        <td><?php echo e($report->created_at->format('F j, Y h:i A')); ?></td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="<?php echo e(route('superadmin.incident_reports.view', $report->id)); ?>" 
                                                   class="btn btn-sm btn-info" target="_blank">
                                                    <i class="fas fa-eye"></i> View
                                                </a>
                                                <a href="<?php echo e(route('superadmin.incident_reports.download', $report->id)); ?>" 
                                                   class="btn btn-sm btn-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="8" class="text-center">No reports found</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <a href="<?php echo e(route('superadmin.dashboard')); ?>" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Dashboard
                        </a>
                        <div>
                            <a href="<?php echo e(route('superadmin.emergencycall.index')); ?>" class="btn btn-outline-primary me-2">
                                <i class="fas fa-phone"></i> Emergency Calls
                            </a>
                            <a href="<?php echo e(route('superadmin.emergencymessage.index')); ?>" class="btn btn-outline-info">
                                <i class="fas fa-comment"></i> Emergency Messages
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php $__env->startSection('scripts'); ?>
<script>
    $(document).ready(function() {
        $('#reportsTable').DataTable({
            order: [[6, 'desc']], // Sort by Generation Date by default
            responsive: true,
            language: {
                search: "Search reports:",
                lengthMenu: "Show _MENU_ reports per page",
                info: "Showing _START_ to _END_ of _TOTAL_ reports"
            }
        });
    });
</script>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.superadmin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\heroes-app\resources\views/super-admin/incidents/list.blade.php ENDPATH**/ ?>