@extends('layouts.mdrrmo')

@section('content')
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">All Incident Reports</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title mb-4">Complete List of Generated Incident Reports</h5>
                    
                    @if(session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    
                    @if(session('error'))
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ session('error') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered" id="reportsTable">
                            <thead class="table-light">
                                <tr>
                                    <th>Report Number</th>
                                    <th>Case Number</th>
                                    <th>Incident Type</th>
                                    <th>Source Type</th>
                                    <th>Contact</th>
                                    <th>Generated By</th>
                                    <th>Generation Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($reports as $report)
                                    <tr>
                                        <td>{{ $report->report_number }}</td>
                                        <td>{{ $report->incidentCase->case_number }}</td>
                                        <td>{{ $report->incidentCase->incidentType->name }}</td>
                                        <td>
                                            <span class="badge bg-{{ $report->source_type == 'call' ? 'success' : ($report->source_type == 'message' ? 'info' : 'secondary') }}">
                                                {{ ucfirst($report->source_type) }}
                                            </span>
                                        </td>
                                        <td>
                                            @if($report->source_type == 'call' && $report->source)
                                                {{ $report->source->caller_contact }}
                                            @elseif($report->source_type == 'message' && $report->source)
                                                {{ $report->source->sender_contact }}
                                            @else
                                                N/A
                                            @endif
                                        </td>
                                        <td>{{ $report->user->profile->firstname.' '.$report->user->profile->lastname ?? 'System' }}</td>
                                        <td>{{ $report->created_at->format('F j, Y h:i A') }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a href="{{ route('mdrrmo.incident_reports.view', $report->id) }}" 
                                                   class="btn btn-sm btn-info" target="_blank">
                                                    <i class="fas fa-eye"></i> View
                                                </a>
                                                <a href="{{ route('mdrrmo.incident_reports.download', $report->id) }}" 
                                                   class="btn btn-sm btn-success">
                                                    <i class="fas fa-download"></i> Download
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="8" class="text-center">No reports found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <a href="{{ route('admin.mdrrmo') }}" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Dashboard
                        </a>
                        <div>
                            <a href="{{ route('mdrrmo.emergencycall.index') }}" class="btn btn-outline-primary me-2">
                                <i class="fas fa-phone"></i> Emergency Calls
                            </a>
                            <a href="{{ route('mdrrmo.emergencymessage.index') }}" class="btn btn-outline-info">
                                <i class="fas fa-comment"></i> Emergency Messages
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        $('#reportsTable').DataTable({
            order: [[6, 'desc']], // Sort by Generation Date by default
            responsive: true,
            language: {
                search: "Search reports:",
                lengthMenu: "Show _MENU_ reports per page",
                info: "Showing _START_ to _END_ of _TOTAL_ reports"
            }
        });
    });
</script>
@endsection